### ISSUE TITLE
game system explanation

### ISSUE THREAD

**Issue by ghost** [alvin0319/GodWar#2]
can you explain how the game works? what the players are supposed to do and what to not do? how to trigger the gods skills? how to get the blazing rod? 

so far all i know is that i have to craft some blocks to get to the other team's base and somehow destroy a diamond block by *hands* **(destroying a diamond block with hands will take forever and kind of impossible? since they will still respawn when they die..)**, but i have no idea about the other stuff such as the gods skills and how they have 2 skills and how they work (or any other feature i missed).

a detailed explanation would be much appreciated

**Comment by alvin0319** [comment]
This plugin isn't finished yet, but I will complete soon.

**Comment by alvin0319** [comment]
closed via https://github.com/alvin0319/GodWar/commit/55a388a9ee4fbf43a3f774ae7de6c840661da065
